# Identificação do projeto
sonar.projectKey=HenriqueOliveiraa_API-Carros
sonar.organization=henriqueoliveiraa

# Nome e versão
sonar.projectName=API Carros
sonar.projectVersion=1.0

# Código fonte
sonar.sources=src/main/java
sonar.tests=src/test/java

# Linguagem
sonar.language=java

# Encoding
sonar.sourceEncoding=UTF-8

# Cobertura de testes (Jacoco)
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusões (opcional)
sonar.exclusions=**/config/**, **/dto/**

# Test exclusions (opcional)
sonar.test.exclusions=**/*Test.java